### ISSUE TITLE
 java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/renderscript/RenderScript;

### ISSUE THREAD

**Issue by bayshier** [wangmingshuo/cupertinodialog#3]
at com.hanter.android.radwidget.cupertino.blur.SupportRenderScriptBlur.<init>(SupportRenderScriptBlur.java:32)
                                                                                                    	at com.hanter.android.radwidget.cupertino.CupertinoAlertDialog.initViews(CupertinoAlertDialog.java:112)
                                                                                                    	at com.hanter.android.radwidget.cupertino.CupertinoAlertDialog.onCreateView(CupertinoAlertDialog.java:101)

**Comment by classops** [comment]
try to change version to 1.0.1：
```
implementation 'com.github.wangmingshuo:CupertinoDialog:1.0.1'
```
